# Generated by Django 5.0.6 on 2024-06-12 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('valoracion', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Valoración')),
                ('enlace', models.URLField(max_length=255, verbose_name='Enlace')),
                ('imagen', models.ImageField(upload_to='cursos/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='CursoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.categoria')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.curso')),
            ],
            options={
                'verbose_name': 'Curso-Categoría',
                'verbose_name_plural': 'Cursos-Categorías',
                'db_table': 'CursoCategoria',
                'unique_together': {('curso', 'categoria')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='categorias',
            field=models.ManyToManyField(related_name='cursos', through='App1.CursoCategoria', to='App1.categoria'),
        ),
        migrations.CreateModel(
            name='UsuarioCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.usuarios')),
            ],
            options={
                'verbose_name': 'Usuario-Curso',
                'verbose_name_plural': 'Usuarios-Cursos',
                'db_table': 'UsuarioCurso',
                'unique_together': {('usuario', 'curso')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='usuarios',
            field=models.ManyToManyField(related_name='cursos_inscritos', through='App1.UsuarioCurso', to='App1.usuarios'),
        ),
    ]
